# Generated by Django 5.1.2 on 2024-12-07 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="remember_me",
            field=models.BooleanField(default=False, verbose_name="Запомнить меня"),
        ),
    ]
