# Generated by Django 5.1.2 on 2024-11-18 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Article",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "title",
                    models.CharField(help_text="Введите заголовок статьи", max_length=150, verbose_name="Заголовок"),
                ),
                ("text", models.TextField(help_text="Добавьте содержание статьи", verbose_name="Содержание")),
                (
                    "preview",
                    models.ImageField(
                        blank=True,
                        help_text="Загрузите превью статьи",
                        null=True,
                        upload_to="articles/",
                        verbose_name="Превью",
                    ),
                ),
                ("created_at", models.DateField(auto_now_add=True)),
                ("is_published", models.BooleanField(default=True)),
                ("views_count", models.IntegerField(default=0)),
            ],
            options={
                "verbose_name": "статья",
                "verbose_name_plural": "статьи",
            },
        ),
    ]
