# Generated by Django 5.1.2 on 2024-11-04 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0002_alter_category_options_alter_product_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="Contacts",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("address", models.TextField(help_text="Введите адрес компании", verbose_name="адрес")),
                (
                    "phone",
                    models.CharField(help_text="Укажите телефон для связи", max_length=20, verbose_name="телефон"),
                ),
                ("email", models.EmailField(max_length=254)),
            ],
            options={
                "verbose_name": "контакты",
                "verbose_name_plural": "контакты",
            },
        ),
    ]
