# Generated by Django 5.1.2 on 2024-12-14 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0004_alter_product_options_product_is_published_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="is_published",
            field=models.BooleanField(default=True, verbose_name="опубликован"),
        ),
    ]
